### ISSUE TITLE
Which C++ compiler is used to handle the nested namespace definitions?

### ISSUE THREAD

**Issue by rhaschke** [TAMS-Group/moveit_task_constructor#1]
With (default) gcc 5 in Xenial, I get thousands of errors due to the nested namespace definitions
`namespace moveit::X {}`
Which compiler do you use for that feature? gcc 6?

**Comment by v4hn** [comment]
Good catch.
I was pretty sure this syntax got approved in C++14 already, but it is only part of C++17.
My workstation uses gcc 7.2 (6.3 back in March), and apparently gcc does not even mention it when compiled with `-std=c++14 -pedantic`.

Should be fixed by 2dfc2f395e105fa1f85033f7b13c9609cc442467
